name: Bug report
description: Create a report to help us improve
labels: ["t/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        **Please update StableCode-VSCode** to the latest version before reporting a bug. Your issue may already be fixed.
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: What went wrong?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
      placeholder: |
        A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: diag
    attributes:
      label: Diagnostic report
      description: |
        Click "Collect Diagnostics" in the Help menu, then paste the output here.

        This is private and only developers can see the report.
      placeholder: |
        REQUIRED. Paste here.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Screenshots and additional context (optional)
      description: Add any other context about the problem here, such as screenshots.
    validations:
      required: false
